name: Feature request
description: Suggest an idea or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing a feature. Please include context and expected behavior.
  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
      description: What problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Screenshots, references, or related issues.
    validations:
      required: false
